name: Build ModGG Client

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Change Gradle Wrapper permissions
      run: chmod +x gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Upload JAR
      uses: actions/upload-artifact@v4
      with:
        name: ModGG-Client-JAR
        path: build/libs/*.jar
